server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761
--- 
spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/dwsc
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
  jpa: 
    hibernate: 
      ddl-auto: update