package BufferApp;


// TODO: Auto-generated Javadoc
/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* martes 29 de noviembre de 2016 11H21' CET
*/

public interface BufferOperations 
{
  
  /**
   * Num elementos.
   *
   * @return El número de elementos
   */
  int num_elementos ();
  
  /**
   * Introduce elemento en la cola
   *
   * @param elemento the elemento
   * @return true, if successful
   */
  boolean put (String elemento);
  
  /**
   * Saca el primer elemento de la cola
   *
   * @param elemento the elemento
   * @return true, if successful
   */
  boolean get (org.omg.CORBA.StringHolder elemento);
  
  /**
   * Lee el primer elemento de la cola
   *
   * @param elemento the elemento
   * @return true, if successful
   */
  boolean read (org.omg.CORBA.StringHolder elemento);
  
  /**
   * Apaga el servidor Corba
   */
  void shutdown ();
} // interface BufferOperations
